wandb_active: false
wandb_project_name: codon_transformer
wandb_entity_name: null
wandb_model_tag: null
checkpoint_dir: codon_transformer
load_pt_checkpoint: null
load_ds_checkpoint: null
node_local_path: null
num_nodes: 1
compute_throughput: false
profiling_path: null
enable_perplexity: true
log_every_n_steps: 50
val_check_interval: null
limit_val_batches: null
check_val_every_n_epoch: 1
checkpoint_every_n_train_steps: null
checkpoint_every_n_epochs: null
deepspeed_flops_profile: false
tokenizer_file: /home/xlian/genslm/genslm/tokenizer_files/codon_wordlevel_69vocab.json
train_file: train.fasta
val_file: val.fasta
test_file: test.fasta
kmer_size: 3
small_subset: 0
enable_blast: false
blast_validation_file: blast_file.fasta
num_blast_seqs_per_gpu: 5
blast_exe_path: blastn
random_seed: 0
model_config_json: model.json
batch_size: 8
epochs: 5
max_steps: -1
gradient_clip_value: 0.0
block_size: 512
accumulate_grad_batches: 1
learning_rate: 5.0e-05
precision: 16
warm_up_lr: null
lr_plateau: null
lr_cosine_with_warmup: null
deepspeed_cfg_file: null
deepspeed_stage: 3
offload_parameters: false
offload_optimizer: false
offload_device: cpu
nvme_path: /local/scratch
partition_activations: false
num_test_seqs_per_gpu: 0
custom_seq_name: SyntheticSeq
num_data_workers: 4
prefetch_factor: 4
pin_memory: true
persistent_workers: true
